version: '3'
services:
  phprc:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../code:/root/code:delegated
#    ports:
#       - "${HTTP_PORT}:80"
    networks:
      - frontend
#      - backend


networks:
  frontend:
    driver: "bridge"
#  backend:
#    driver: "bridge"

